/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      "Goods",
      [
        {
          title: "Футболка",
          price: 500,
          image: "/img/ddrbs-000.jpg",
          description: "Классическая футболка",
          color: "Белый",
          categoryId: 1,
          genderId: 1,
          brandId: 1,
          size: "M",
          quantity: 1,
        },
        {
          title: "Футболка",
          price: 500,
          image: "/img/ddrbs-000.jpg",
          description: "Классическая футболка",
          color: "Черный",
          categoryId: 1,
          genderId: 1,
          brandId: 1,
          size: "X",
          quantity: 1,
        },
        {
          title: "Джинсы",
          price: 1500,
          image: "/img/ddrbs-000.jpg",
          description: "Стандартные джинсы",
          color: "Синий",
          categoryId: 2,
          genderId: 1,
          brandId: 2,
          size: "M",
          quantity: 1,
        },
        {
          title: "Платье",
          price: 2000,
          image: "/img/ddrbs-000.jpg",
          description: "Стильное платье для вечеринок",
          color: "Красный",
          categoryId: 3,
          genderId: 2,
          brandId: 3,
          size: "M",
          quantity: 5,
        },
        {
          title: "Куртка",
          price: 3000,
          image: "/img/ddrbs-000.jpg",
          description: "Теплая зимняя куртка",
          color: "Черный",
          categoryId: 4,
          genderId: 1,
          brandId: 4,
          size: "M",
          quantity: 1,
        },
        {
          title: "Юбка",
          price: 1000,
          image: "/img/ddrbs-000.jpg",
          description: "Повседневная юбка",
          color: "Серый",
          categoryId: 5,
          genderId: 2,
          brandId: 5,
          size: "S",
          quantity: 1,
        },
        {
          title: "Рубашка",
          price: 800,
          image: "/img/ddrbs-000.jpg",
          description: "Простая рубашка для делового стиля",
          color: "Белый",
          categoryId: 6,
          genderId: 1,
          brandId: 6,
          size: "L",
          quantity: 1,
        },
        {
          title: "Блузка",
          price: 1200,
          image: "/img/ddrbs-000.jpg",
          description: "Стильная блузка с акцентами",
          color: "Розовый",
          categoryId: 7,
          genderId: 2,
          brandId: 7,
          size: "S",
          quantity: 3,
        },
        {
          title: "Спортивные штаны",
          price: 900,
          image: "/img/ddrbs-000.jpg",
          description: "Удобные спортивные штаны",
          color: "Черный",
          categoryId: 8,
          genderId: 1,
          brandId: 8,
          size: "M",
          quantity: 2,
        },
        {
          title: "Шапка",
          price: 300,
          image: "/img/ddrbs-000.jpg",
          description: "Теплая вязаная шапка",
          color: "Серый",
          categoryId: 9,
          genderId: 1,
          brandId: 9,
          size: "XS",
          quantity: 5,
        },
        {
          title: "Ботинки",
          price: 2500,
          image: "/img/ddrbs-000.jpg",
          description: "Кожаные ботинки на каждый день",
          color: "Коричневый",
          categoryId: 10,
          genderId: 1,
          brandId: 10,
          size: 42,
          quantity: 10,
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("Goods", null, {});
  },
};
